### ISSUE TITLE
Feature: Allow/parse Companion variables in Update Control Node value

### ISSUE THREAD

**Issue by estilles** [bitfocus/companion-module-singularlive-studio#11]
**Describe the feature**
I would like to be able to use Companion custom variables (or any other variable for than matter) within the value option of the Update Control Node action.

**Usecases**
The screen capture below demonstrate a possible use case.

![image](https://user-images.githubusercontent.com/5514878/137269460-7eaf5143-67a3-4178-92dd-d16c25c3e9c7.png)

**Comment by fredrikmediaa** [comment]
Thanks for the suggestion, and for the solution @estilles.

Fixed: #12
