### ISSUE TITLE
Incrementing a numeric value in a control field

### ISSUE THREAD

**Issue by BennyCoin** [bitfocus/companion-module-singularlive-studio#2]
Hi, 
is there a facility to increment (or decrease) a numeric value in a Number field via Companion ?

I know I can use 'Update Control Node' to inject a specific value but this doesn't allow me to increment an existing value by 1 or other steps - at least that I can see.

thanks

**Comment by fredrikmediaa** [comment]
Sorry for not answering you before, I haven't been active on this repo for a while. Unfortunately, as far as I know there is no commands in the singular api for increment or decrement a control node value. To be able to do this Companion and this module has to be aware of what state the control node, and this is not a feature I have added.

I would recommend that you make a button and tie it to a composition script to increasing or decreasing your value. If you have problems with composition scripts let me know. Good luck!

**Comment by lbennexigo** [comment]
@fredrikmediaa, I an also trying to this with little success!! I can increase a value in script, but I can't figure out how to tie a button to script in singular, please help!!
